[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "akii"
version = "0.1.5"
description = "HTTP header analyzer"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"

dependencies = [
    "requests>=2.32.0",
    "PyYAML>=6.0",
    "colorama>=0.4.6",
]

[project.scripts]
akii = "akii.core.cli.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
akii = ["templates/*.yaml"]